const EXERCISES = {
    "01": { id: "01", name: "Squats", target: "Jambes / Fessiers", type: "reps", value: 15, desc: "Fléchissez les jambes en poussant le bassin vers l'arrière.", resp: "Inspire en descendant, souffle en montant.", err: "Décoller les talons, dos rond.", var: "Demi-squat.", tip: "Regard droit devant.", img: "assets/exercises/01-squat.jpg" },
    "02": { id: "02", name: "Fentes arrière", target: "Jambes / Fessiers", type: "reps", value: 12, desc: "Reculez une jambe et fléchissez pour faire un angle de 90°.", resp: "Inspire en reculant, souffle en revenant.", err: "Genou avant qui dépasse le pied.", var: "Faible amplitude.", tip: "Buste bien droit.", img: "assets/exercises/02-fentes.jpg" },
    "03": { id: "03", name: "Pont fessier", target: "Fessiers / Ischios", type: "reps", value: 15, desc: "Allongé sur le dos, levez le bassin en contractant les fessiers.", resp: "Souffle en levant.", err: "Creuser excessivement les lombaires.", var: "Mouvement plus court.", tip: "Poussez sur les talons.", img: "assets/exercises/03-pont.jpg" },
    "04": { id: "04", name: "Pompes classiques", target: "Pectoraux / Triceps", type: "reps", value: 8, desc: "Corps aligné, descendez la poitrine vers le sol.", resp: "Inspire en descendant, souffle en poussant.", err: "Bassin qui tombe.", var: "Sur les genoux.", tip: "Gainez tout le corps.", img: "assets/exercises/04-pompes.jpg" },
    "05": { id: "05", name: "Dips sur chaise", target: "Triceps / Épaules", type: "reps", value: 10, desc: "Dos près de la chaise, fléchissez les bras à 90°.", resp: "Inspire en descendant, souffle en poussant.", err: "S'éloigner de la chaise.", var: "Jambes pliées.", tip: "Contrôlez la descente.", img: "assets/exercises/05-dips.jpg" },
    "06": { id: "06", name: "Bird-Dog", target: "Dos / Sangle", type: "reps", value: 12, desc: "À 4 pattes, tendez un bras et la jambe opposée.", resp: "Souffle lors de l'extension.", err: "Bouger le bassin.", var: "Seulement les bras, puis les jambes.", tip: "Cherchez l'étirement, pas la hauteur.", img: "assets/exercises/06-birddog.jpg" },
    "07": { id: "07", name: "Extension YTW", target: "Chaîne post.", type: "reps", value: 10, desc: "Penché en avant, formez un Y, un T puis un W avec les bras.", resp: "Souffle lors de l'élévation.", err: "Donner des à-coups.", var: "Debout droit.", tip: "Serrez les omoplates.", img: "assets/exercises/07-ytw.jpg" },
    "08": { id: "08", name: "Planche faciale", target: "Gainage", type: "time", value: 30, desc: "En appui sur les avant-bras, corps parfaitement aligné.", resp: "Respiration fluide et continue.", err: "Fesses trop hautes ou bassin creusé.", var: "Sur les genoux.", tip: "Aspirez le nombril.", img: "assets/exercises/08-planche.jpg" },
    "09": { id: "09", name: "Planche latérale", target: "Obliques", type: "time", value: 20, desc: "En appui sur un avant-bras, corps aligné de profil.", resp: "Continue.", err: "Bassin qui s'affaisse.", var: "Genoux au sol.", tip: "Faites les deux côtés (20s chaque).", img: "assets/exercises/09-planchelat.jpg" },
    "10": { id: "10", name: "Dead Bug", target: "Abdominaux", type: "reps", value: 12, desc: "Sur le dos, tendez une jambe et le bras opposé vers le sol.", resp: "Souffle lors de l'extension.", err: "Décoller le bas du dos.", var: "Bouger une jambe à la fois.", tip: "Lombaires collées au sol !", img: "assets/exercises/10-deadbug.jpg" },
    "11": { id: "11", name: "Pike Push-ups", target: "Épaules", type: "reps", value: 8, desc: "En V inversé, fléchissez les bras pour approcher la tête du sol.", resp: "Inspire en descendant.", err: "Écarter trop les coudes.", var: "Mouvement sans poids debout.", tip: "Gardez les jambes tendues.", img: "assets/exercises/11-pike.jpg" },
    "12": { id: "12", name: "Commando Plank", target: "Bras / Gainage", type: "reps", value: 8, desc: "Passez de la planche avant-bras à la planche sur les mains.", resp: "Souffle en poussant.", err: "Trop balancer le bassin.", var: "Gainage statique.", tip: "Alternez le bras qui pousse.", img: "assets/exercises/12-commando.jpg" },
    "13": { id: "13", name: "Elevage mollets", target: "Mollets", type: "reps", value: 20, desc: "Montez sur la pointe des pieds, redescendez lentement.", resp: "Souffle en montant.", err: "Retomber lourdement.", var: "S'appuyer au mur.", tip: "Pause d'1 seconde en haut.", img: "assets/exercises/13-mollets.jpg" },
    "14": { id: "14", name: "Mountain Climbers", target: "Cardio / Abdos", type: "time", value: 30, desc: "En position pompe, ramenez alternativement les genoux vers la poitrine.", resp: "Rythmée.", err: "Rebondir avec le bassin.", var: "Mouvement lent.", tip: "Gardez les épaules au-dessus des mains.", img: "assets/exercises/14-climbers.jpg" },
    "15": { id: "15", name: "Jumping Jacks", target: "Cardio", type: "time", value: 30, desc: "Écartez les jambes et levez les bras en sautant.", resp: "Rythmée.", err: "Genoux qui rentrent vers l'intérieur.", var: "Pas latéraux sans saut.", tip: "Restez léger sur les pointes.", img: "assets/exercises/15-jacks.jpg" },
    "16": { id: "16", name: "Montées de genoux", target: "Cardio", type: "time", value: 25, desc: "Courez sur place en levant les genoux à hauteur du bassin.", resp: "Rythmée.", err: "Se pencher en arrière.", var: "Marche rapide.", tip: "Utilisez vos bras.", img: "assets/exercises/16-genoux.jpg" }
};

const DEFAULT_PROGRAM = ["01", "04", "03", "06", "05", "08", "02", "15"];